/**
* CREATED BY    : Karthick D K 
* CREATED DATE  : 20 JUNE 2023
* MODIFIED BY   : Karthick D K
* MODIFIED DATE : 20 JUNE 2023
* DESCRIPTION   : This page will be common for all the pages
**/

import '@/styles/globals.css'
import '@/styles/Home.module.css'
import type { AppProps } from 'next/app'
import AppBar from '@mui/material/AppBar';
import Box from '@mui/material/Box';
import Toolbar from '@mui/material/Toolbar';
import Typography from '@mui/material/Typography';
import IconButton from '@mui/material/IconButton';
import { createTheme, ThemeProvider } from '@mui/material/styles';
import Image from 'next/image';
import redBusLogo from '../assets/images/rdc-redbus-logo.svg'
import busTicketLogo from '../assets/images/bus-tick-logo.svg'
import cabRentalLogo from '../assets/images/cab-rent-logo.svg'
import trainTicketLogo from '../assets/images/train-tic-logo.svg'
import List from '@mui/material/List';
import ListItem from '@mui/material/ListItem';
import { Grid } from '@mui/material';
import MenuItem from '@mui/material/MenuItem';
import Menu from '@mui/material/Menu';
import { useState } from 'react'
import Head from 'next/head';

const theme = createTheme({
  typography: {
    fontFamily: 'Montserrat'
  },
});


export default function App({ Component, pageProps }: AppProps) {

  const [anchorEl, setAnchorEl] = useState<null | HTMLElement>(null);


  const handleMenu = (event: React.MouseEvent<HTMLElement>) => {
    setAnchorEl(event.currentTarget);
  };

  const handleClose = () => {
    setAnchorEl(null);
  };

  return (
    <>
      <Head>
        <title>Red Bus</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="../assets/images/rdc-redbus-logo.svg" />
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link rel="preconnect" href="https://fonts.gstatic.com"></link>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet"></link>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
      </Head>
      <ThemeProvider theme={theme}>
        <Box sx={{ flexGrow: 2 }}>
          <AppBar position="static" variant='elevation' sx={{ background: 'white', height: '100px', color: 'black', overflow: 'hidden' }}>
            <Toolbar >
              <IconButton
                size="large"
                edge="start"
                color="inherit"
                aria-label="menu"
                sx={{ mr: 2 }}
              >
                <Image alt='redbus' src={redBusLogo} width={70} height={70} />
              </IconButton>
              <Typography variant="h6" component="div" sx={{ flexGrow: 2, display: 'flex', alignItems: 'center' }}>
                <List sx={{ display: 'flex', paddingLeft: '90px' }}>
                  <ListItem sx={{ display: 'flex' }} button>
                    <Grid container>
                      <Grid item xs={12} sx={{ display: 'flex', justifyContent: 'center' }}>
                        <Image alt='bustic' className="black-and-white-image" src={busTicketLogo} width={30} height={30} color='black' /><br />
                      </Grid>
                      <Grid item xs={12} sx={{ display: 'flex', justifyContent: 'center' }}>
                        <Typography variant="caption" component="div" sx={{ fontSize: '14px' }}>Bus Tickets</Typography>
                      </Grid>
                    </Grid>
                  </ListItem>
                  <ListItem button>
                    <Grid container>
                      <Grid item xs={12} sx={{ display: 'flex', justifyContent: 'center' }}>
                        <Image alt='cabrent' className="black-and-white-image" src={cabRentalLogo} width={30} height={30} color='black' /><br />
                      </Grid>
                      <Grid item xs={12} sx={{ display: 'flex', justifyContent: 'center' }}>
                        <Typography variant="caption" component="div" sx={{ fontSize: '14px' }}>Cab Rental</Typography>
                      </Grid>
                    </Grid>
                  </ListItem>
                  <ListItem button>
                    <Grid container>
                      <Grid item xs={12} sx={{ display: 'flex', justifyContent: 'center' }}>
                        <Image alt='bustic' className="black-and-white-image" src={trainTicketLogo} width={30} height={30} color='black' /><br />
                      </Grid>
                      <Grid item xs={12} sx={{ display: 'flex', justifyContent: 'center' }}>
                        <Typography variant="caption" component="div" sx={{ fontSize: '14px' }}>Train Tickets</Typography>
                      </Grid>
                    </Grid>
                  </ListItem>
                </List>
              </Typography>
              <span className="material-symbols-outlined">support_agent</span>
              &nbsp;Help
              <span style={{ paddingLeft: '40px', cursor: 'pointer' }} onClick={handleMenu} className="material-symbols-outlined">support_agent</span>
              &nbsp;
              <span style={{ cursor: 'pointer' }} onClick={handleMenu} >Account</span>
              <span className="material-symbols-outlined">
                expand_more
              </span>
              <Menu
                id="menu-appbar"
                anchorEl={anchorEl}
                anchorOrigin={{
                  vertical: 'top',
                  horizontal: 'right',
                }}
                keepMounted
                transformOrigin={{
                  vertical: 'top',
                  horizontal: 'right',
                }}
                open={Boolean(anchorEl)}
                onClose={handleClose}
              >
                <MenuItem onClick={handleClose}>Profile</MenuItem>
                <MenuItem onClick={handleClose}>My account</MenuItem>
              </Menu>
            </Toolbar>
          </AppBar>
        </Box>
        <Box sx={{ backgroundColor: 'whitesmoke', height: 'calc(100vh - 100px)' }}>
          <Component {...pageProps} />
        </Box>
      </ThemeProvider >
    </>
  )
}
