/**
* CREATED BY    : Karthick D K 
* CREATED DATE  : 20 JUNE 2023
* MODIFIED BY   : Karthick D K
* MODIFIED DATE : 20 JUNE 2023
* DESCRIPTION   : This config will contain bus list config
**/

export class BusListConfig {
    BUS_LIST_CONFIG = [
        {
            busID: 1,
            firstName: 'VKV Travels',
            secondName: 'Bharat Benz A/C Sleeper (2+1)',
            thirdName: '',
            firstDeparture: '20:40',
            secondDeparture: '',
            thirdDeparture: 'Udayarpatti',
            firstDuration: '10h 35m',
            secondDuration: '',
            thirdDuration: '',
            firstArrival: '07:15',
            secondArrival: '20-JUL',
            thirdArrival: 'Koyambedu',
            firstRatings: '4.5',
            secondRatings: '440',
            thirdRatings: '',
            firstFair: 'Starts from INR 1090',
            secondFair: '',
            thirdFair: '',
            firstSeatsAvailable: '13 Seats available',
            secondSeatsAvailable: '5 Single',
            thirdSeatsAvailable: '',
        },
        {
            busID: 2,
            firstName: 'VKV Travels',
            secondName: 'Bharat Benz A/C Sleeper (2+1)',
            thirdName: '',
            firstDeparture: '20:40',
            secondDeparture: '',
            thirdDeparture: 'Udayarpatti',
            firstDuration: '10h 35m',
            secondDuration: '',
            thirdDuration: '',
            firstArrival: '07:15',
            secondArrival: '20-JUL',
            thirdArrival: 'Koyambedu',
            firstRatings: '4.5',
            secondRatings: '440',
            thirdRatings: '',
            firstFair: 'Starts from INR 1090',
            secondFair: '',
            thirdFair: '',
            firstSeatsAvailable: '13 Seats available',
            secondSeatsAvailable: '5 Single',
            thirdSeatsAvailable: '',
        },
        {
            busID: 3,
            firstName: 'VKV Travels',
            secondName: 'Bharat Benz A/C Sleeper (2+1)',
            thirdName: '',
            firstDeparture: '20:40',
            secondDeparture: '',
            thirdDeparture: 'Udayarpatti',
            firstDuration: '10h 35m',
            secondDuration: '',
            thirdDuration: '',
            firstArrival: '07:15',
            secondArrival: '20-JUL',
            thirdArrival: 'Koyambedu',
            firstRatings: '4.5',
            secondRatings: '440',
            thirdRatings: '',
            firstFair: 'Starts from INR 1090',
            secondFair: '',
            thirdFair: '',
            firstSeatsAvailable: '13 Seats available',
            secondSeatsAvailable: '5 Single',
            thirdSeatsAvailable: '',
        },
        {
            busID: 4,
            firstName: 'VKV Travels',
            secondName: 'Bharat Benz A/C Sleeper (2+1)',
            thirdName: '',
            firstDeparture: '20:40',
            secondDeparture: '',
            thirdDeparture: 'Udayarpatti',
            firstDuration: '10h 35m',
            secondDuration: '',
            thirdDuration: '',
            firstArrival: '07:15',
            secondArrival: '20-JUL',
            thirdArrival: 'Koyambedu',
            firstRatings: '4.5',
            secondRatings: '440',
            thirdRatings: '',
            firstFair: 'Starts from INR 1090',
            secondFair: '',
            thirdFair: '',
            firstSeatsAvailable: '13 Seats available',
            secondSeatsAvailable: '5 Single',
            thirdSeatsAvailable: '',
        },
        {
            busID: 5,
            firstName: 'VKV Travels',
            secondName: 'Bharat Benz A/C Sleeper (2+1)',
            thirdName: '',
            firstDeparture: '20:40',
            secondDeparture: '',
            thirdDeparture: 'Udayarpatti',
            firstDuration: '10h 35m',
            secondDuration: '',
            thirdDuration: '',
            firstArrival: '07:15',
            secondArrival: '20-JUL',
            thirdArrival: 'Koyambedu',
            firstRatings: '4.5',
            secondRatings: '440',
            thirdRatings: '',
            firstFair: 'Starts from INR 1090',
            secondFair: '',
            thirdFair: '',
            firstSeatsAvailable: '13 Seats available',
            secondSeatsAvailable: '5 Single',
            thirdSeatsAvailable: '',
        },
        {
            busID: 6,
            firstName: 'VKV Travels',
            secondName: 'Bharat Benz A/C Sleeper (2+1)',
            thirdName: '',
            firstDeparture: '20:40',
            secondDeparture: '',
            thirdDeparture: 'Udayarpatti',
            firstDuration: '10h 35m',
            secondDuration: '',
            thirdDuration: '',
            firstArrival: '07:15',
            secondArrival: '20-JUL',
            thirdArrival: 'Koyambedu',
            firstRatings: '4.5',
            secondRatings: '440',
            thirdRatings: '',
            firstFair: 'Starts from INR 1090',
            secondFair: '',
            thirdFair: '',
            firstSeatsAvailable: '13 Seats available',
            secondSeatsAvailable: '5 Single',
            thirdSeatsAvailable: '',
        },
        {
            busID: 7,
            firstName: 'VKV Travels',
            secondName: 'Bharat Benz A/C Sleeper (2+1)',
            thirdName: '',
            firstDeparture: '20:40',
            secondDeparture: '',
            thirdDeparture: 'Udayarpatti',
            firstDuration: '10h 35m',
            secondDuration: '',
            thirdDuration: '',
            firstArrival: '07:15',
            secondArrival: '20-JUL',
            thirdArrival: 'Koyambedu',
            firstRatings: '4.5',
            secondRatings: '440',
            thirdRatings: '',
            firstFair: 'Starts from INR 1090',
            secondFair: '',
            thirdFair: '',
            firstSeatsAvailable: '13 Seats available',
            secondSeatsAvailable: '5 Single',
            thirdSeatsAvailable: '',
        },
        {
            busID: 8,
            firstName: 'VKV Travels',
            secondName: 'Bharat Benz A/C Sleeper (2+1)',
            thirdName: '',
            firstDeparture: '20:40',
            secondDeparture: '',
            thirdDeparture: 'Udayarpatti',
            firstDuration: '10h 35m',
            secondDuration: '',
            thirdDuration: '',
            firstArrival: '07:15',
            secondArrival: '20-JUL',
            thirdArrival: 'Koyambedu',
            firstRatings: '4.5',
            secondRatings: '440',
            thirdRatings: '',
            firstFair: 'Starts from INR 1090',
            secondFair: '',
            thirdFair: '',
            firstSeatsAvailable: '13 Seats available',
            secondSeatsAvailable: '5 Single',
            thirdSeatsAvailable: '',
        },
        {
            busID: 9,
            firstName: 'VKV Travels',
            secondName: 'Bharat Benz A/C Sleeper (2+1)',
            thirdName: '',
            firstDeparture: '20:40',
            secondDeparture: '',
            thirdDeparture: 'Udayarpatti',
            firstDuration: '10h 35m',
            secondDuration: '',
            thirdDuration: '',
            firstArrival: '07:15',
            secondArrival: '20-JUL',
            thirdArrival: 'Koyambedu',
            firstRatings: '4.5',
            secondRatings: '440',
            thirdRatings: '',
            firstFair: 'Starts from INR 1090',
            secondFair: '',
            thirdFair: '',
            firstSeatsAvailable: '13 Seats available',
            secondSeatsAvailable: '5 Single',
            thirdSeatsAvailable: '',
        },
        {
            busID: 10,
            firstName: 'VKV Travels',
            secondName: 'Bharat Benz A/C Sleeper (2+1)',
            thirdName: '',
            firstDeparture: '20:40',
            secondDeparture: '',
            thirdDeparture: 'Udayarpatti',
            firstDuration: '10h 35m',
            secondDuration: '',
            thirdDuration: '',
            firstArrival: '07:15',
            secondArrival: '20-JUL',
            thirdArrival: 'Koyambedu',
            firstRatings: '4.5',
            secondRatings: '440',
            thirdRatings: '',
            firstFair: 'Starts from INR 1090',
            secondFair: '',
            thirdFair: '',
            firstSeatsAvailable: '13 Seats available',
            secondSeatsAvailable: '5 Single',
            thirdSeatsAvailable: '',
        },
        {
            busID: 11,
            firstName: 'VKV Travels',
            secondName: 'Bharat Benz A/C Sleeper (2+1)',
            thirdName: '',
            firstDeparture: '20:40',
            secondDeparture: '',
            thirdDeparture: 'Udayarpatti',
            firstDuration: '10h 35m',
            secondDuration: '',
            thirdDuration: '',
            firstArrival: '07:15',
            secondArrival: '20-JUL',
            thirdArrival: 'Koyambedu',
            firstRatings: '4.5',
            secondRatings: '440',
            thirdRatings: '',
            firstFair: 'Starts from INR 1090',
            secondFair: '',
            thirdFair: '',
            firstSeatsAvailable: '13 Seats available',
            secondSeatsAvailable: '5 Single',
            thirdSeatsAvailable: '',
        },
        {
            busID: 12,
            firstName: 'VKV Travels',
            secondName: 'Bharat Benz A/C Sleeper (2+1)',
            thirdName: '',
            firstDeparture: '20:40',
            secondDeparture: '',
            thirdDeparture: 'Udayarpatti',
            firstDuration: '10h 35m',
            secondDuration: '',
            thirdDuration: '',
            firstArrival: '07:15',
            secondArrival: '20-JUL',
            thirdArrival: 'Koyambedu',
            firstRatings: '4.5',
            secondRatings: '440',
            thirdRatings: '',
            firstFair: 'Starts from INR 1090',
            secondFair: '',
            thirdFair: '',
            firstSeatsAvailable: '13 Seats available',
            secondSeatsAvailable: '5 Single',
            thirdSeatsAvailable: '',
        }
    ]
}