export class BusListConfig {
    BUS_LIST_CONFIG = [
        {
            firstName: 'VKV Travels',
            secondName: 'Bharat Benz A/C Sleeper (2+1)',
            thirdName: '',
            firstDeparture: '20:40',
            secondDeparture: '',
            thirdDeparture: 'Udayarpatti',
            firstDuration: '10h 35m',
            secondDuration: '',
            thirdDuration: '',
            firstArrival: '07:15',
            secondArrival: '20-JUL',
            thirdArrival: 'Koyambedu',
            firstRatings: '4.5',
            secondRatings: '440',
            thirdRatings: '',
            firstFair: 'Starts from INR 1090',
            secondFair: '',
            thirdFair: '',
            firstSeatsAvailable: '13 Seats available',
            secondSeatsAvailable: '5 Single',
            thirdSeatsAvailable: '',
        },
        {
            firstName: 'VKV Travels',
            secondName: 'Bharat Benz A/C Sleeper (2+1)',
            thirdName: '',
            firstDeparture: '20:40',
            secondDeparture: '',
            thirdDeparture: 'Udayarpatti',
            firstDuration: '10h 35m',
            secondDuration: '',
            thirdDuration: '',
            firstArrival: '07:15',
            secondArrival: '20-JUL',
            thirdArrival: 'Koyambedu',
            firstRatings: '4.5',
            secondRatings: '440',
            thirdRatings: '',
            firstFair: 'Starts from INR 1090',
            secondFair: '',
            thirdFair: '',
            firstSeatsAvailable: '13 Seats available',
            secondSeatsAvailable: '5 Single',
            thirdSeatsAvailable: '',
        },
        {
            firstName: 'VKV Travels',
            secondName: 'Bharat Benz A/C Sleeper (2+1)',
            thirdName: '',
            firstDeparture: '20:40',
            secondDeparture: '',
            thirdDeparture: 'Udayarpatti',
            firstDuration: '10h 35m',
            secondDuration: '',
            thirdDuration: '',
            firstArrival: '07:15',
            secondArrival: '20-JUL',
            thirdArrival: 'Koyambedu',
            firstRatings: '4.5',
            secondRatings: '440',
            thirdRatings: '',
            firstFair: 'Starts from INR 1090',
            secondFair: '',
            thirdFair: '',
            firstSeatsAvailable: '13 Seats available',
            secondSeatsAvailable: '5 Single',
            thirdSeatsAvailable: '',
        },
        {
            firstName: 'VKV Travels',
            secondName: 'Bharat Benz A/C Sleeper (2+1)',
            thirdName: '',
            firstDeparture: '20:40',
            secondDeparture: '',
            thirdDeparture: 'Udayarpatti',
            firstDuration: '10h 35m',
            secondDuration: '',
            thirdDuration: '',
            firstArrival: '07:15',
            secondArrival: '20-JUL',
            thirdArrival: 'Koyambedu',
            firstRatings: '4.5',
            secondRatings: '440',
            thirdRatings: '',
            firstFair: 'Starts from INR 1090',
            secondFair: '',
            thirdFair: '',
            firstSeatsAvailable: '13 Seats available',
            secondSeatsAvailable: '5 Single',
            thirdSeatsAvailable: '',
        },
        {
            firstName: 'VKV Travels',
            secondName: 'Bharat Benz A/C Sleeper (2+1)',
            thirdName: '',
            firstDeparture: '20:40',
            secondDeparture: '',
            thirdDeparture: 'Udayarpatti',
            firstDuration: '10h 35m',
            secondDuration: '',
            thirdDuration: '',
            firstArrival: '07:15',
            secondArrival: '20-JUL',
            thirdArrival: 'Koyambedu',
            firstRatings: '4.5',
            secondRatings: '440',
            thirdRatings: '',
            firstFair: 'Starts from INR 1090',
            secondFair: '',
            thirdFair: '',
            firstSeatsAvailable: '13 Seats available',
            secondSeatsAvailable: '5 Single',
            thirdSeatsAvailable: '',
        },
        {
            firstName: 'VKV Travels',
            secondName: 'Bharat Benz A/C Sleeper (2+1)',
            thirdName: '',
            firstDeparture: '20:40',
            secondDeparture: '',
            thirdDeparture: 'Udayarpatti',
            firstDuration: '10h 35m',
            secondDuration: '',
            thirdDuration: '',
            firstArrival: '07:15',
            secondArrival: '20-JUL',
            thirdArrival: 'Koyambedu',
            firstRatings: '4.5',
            secondRatings: '440',
            thirdRatings: '',
            firstFair: 'Starts from INR 1090',
            secondFair: '',
            thirdFair: '',
            firstSeatsAvailable: '13 Seats available',
            secondSeatsAvailable: '5 Single',
            thirdSeatsAvailable: '',
        },
        {
            firstName: 'VKV Travels',
            secondName: 'Bharat Benz A/C Sleeper (2+1)',
            thirdName: '',
            firstDeparture: '20:40',
            secondDeparture: '',
            thirdDeparture: 'Udayarpatti',
            firstDuration: '10h 35m',
            secondDuration: '',
            thirdDuration: '',
            firstArrival: '07:15',
            secondArrival: '20-JUL',
            thirdArrival: 'Koyambedu',
            firstRatings: '4.5',
            secondRatings: '440',
            thirdRatings: '',
            firstFair: 'Starts from INR 1090',
            secondFair: '',
            thirdFair: '',
            firstSeatsAvailable: '13 Seats available',
            secondSeatsAvailable: '5 Single',
            thirdSeatsAvailable: '',
        },
        {
            firstName: 'VKV Travels',
            secondName: 'Bharat Benz A/C Sleeper (2+1)',
            thirdName: '',
            firstDeparture: '20:40',
            secondDeparture: '',
            thirdDeparture: 'Udayarpatti',
            firstDuration: '10h 35m',
            secondDuration: '',
            thirdDuration: '',
            firstArrival: '07:15',
            secondArrival: '20-JUL',
            thirdArrival: 'Koyambedu',
            firstRatings: '4.5',
            secondRatings: '440',
            thirdRatings: '',
            firstFair: 'Starts from INR 1090',
            secondFair: '',
            thirdFair: '',
            firstSeatsAvailable: '13 Seats available',
            secondSeatsAvailable: '5 Single',
            thirdSeatsAvailable: '',
        },
        {
            firstName: 'VKV Travels',
            secondName: 'Bharat Benz A/C Sleeper (2+1)',
            thirdName: '',
            firstDeparture: '20:40',
            secondDeparture: '',
            thirdDeparture: 'Udayarpatti',
            firstDuration: '10h 35m',
            secondDuration: '',
            thirdDuration: '',
            firstArrival: '07:15',
            secondArrival: '20-JUL',
            thirdArrival: 'Koyambedu',
            firstRatings: '4.5',
            secondRatings: '440',
            thirdRatings: '',
            firstFair: 'Starts from INR 1090',
            secondFair: '',
            thirdFair: '',
            firstSeatsAvailable: '13 Seats available',
            secondSeatsAvailable: '5 Single',
            thirdSeatsAvailable: '',
        },
        {
            firstName: 'VKV Travels',
            secondName: 'Bharat Benz A/C Sleeper (2+1)',
            thirdName: '',
            firstDeparture: '20:40',
            secondDeparture: '',
            thirdDeparture: 'Udayarpatti',
            firstDuration: '10h 35m',
            secondDuration: '',
            thirdDuration: '',
            firstArrival: '07:15',
            secondArrival: '20-JUL',
            thirdArrival: 'Koyambedu',
            firstRatings: '4.5',
            secondRatings: '440',
            thirdRatings: '',
            firstFair: 'Starts from INR 1090',
            secondFair: '',
            thirdFair: '',
            firstSeatsAvailable: '13 Seats available',
            secondSeatsAvailable: '5 Single',
            thirdSeatsAvailable: '',
        },
        {
            firstName: 'VKV Travels',
            secondName: 'Bharat Benz A/C Sleeper (2+1)',
            thirdName: '',
            firstDeparture: '20:40',
            secondDeparture: '',
            thirdDeparture: 'Udayarpatti',
            firstDuration: '10h 35m',
            secondDuration: '',
            thirdDuration: '',
            firstArrival: '07:15',
            secondArrival: '20-JUL',
            thirdArrival: 'Koyambedu',
            firstRatings: '4.5',
            secondRatings: '440',
            thirdRatings: '',
            firstFair: 'Starts from INR 1090',
            secondFair: '',
            thirdFair: '',
            firstSeatsAvailable: '13 Seats available',
            secondSeatsAvailable: '5 Single',
            thirdSeatsAvailable: '',
        },
        {
            firstName: 'VKV Travels',
            secondName: 'Bharat Benz A/C Sleeper (2+1)',
            thirdName: '',
            firstDeparture: '20:40',
            secondDeparture: '',
            thirdDeparture: 'Udayarpatti',
            firstDuration: '10h 35m',
            secondDuration: '',
            thirdDuration: '',
            firstArrival: '07:15',
            secondArrival: '20-JUL',
            thirdArrival: 'Koyambedu',
            firstRatings: '4.5',
            secondRatings: '440',
            thirdRatings: '',
            firstFair: 'Starts from INR 1090',
            secondFair: '',
            thirdFair: '',
            firstSeatsAvailable: '13 Seats available',
            secondSeatsAvailable: '5 Single',
            thirdSeatsAvailable: '',
        }
    ]
}